name: Email Scheduler with Gemini

on:
  schedule:
    # 9:00 AM IST (3:30 UTC)
    - cron: '30 3 * * *'
    # 12:00 PM IST (6:30 UTC)
    - cron: '30 6 * * *'
    # 4:00 PM IST (10:30 UTC)
    - cron: '30 10 * * *'
    # 7:00 PM IST (13:30 UTC)
    - cron: '30 13 * * *'
    # 10:00 PM IST (16:30 UTC)
    - cron: '30 16 * * *'
  workflow_dispatch:
    inputs:
      time_of_day:
        description: 'Time of day (morning, noon, afternoon, evening, night)'
        required: true
        default: 'morning'

jobs:
  generate_and_send:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Generate image
        run: |
          TIME_OF_DAY=${{ github.event.inputs.time_of_day || 'morning' }}
          python scripts/generate_image.py $TIME_OF_DAY
      - name: Commit and push image
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add images/
          git commit -m "Add generated image for $TIME_OF_DAY" || echo "No changes to commit"
          git push
      - name: Send email
        env:
          main_gmail: ${{ secrets.MAIN_GMAIL }}
          app_password: ${{ secrets.APP_PASSWORD }}
          alias_email: ${{ secrets.ALIAS_EMAIL }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GITHUB_PAGES_BASE_URL: ${{ secrets.PAGES_BASE_URL }}
          RECIPIENTS: ${{ secrets.RECIPIENTS }}
        run: |
          TIME_OF_DAY=${{ github.event.inputs.time_of_day || 'morning' }}
          python scripts/send_mail.py $TIME_OF_DAY "$RECIPIENTS"
